--테이블&시퀀스 DROP 및 CREATE
--CUSTOMER
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
CREATE TABLE CUSTOMER(
CID VARCHAR2(50)  PRIMARY KEY,
CPW VARCHAR2(50) NOT NULL,
CNAME VARCHAR2(50) NOT NULL,
CEMAIL VARCHAR2(50) NOT NULL,
CIMAGE1 VARCHAR2(50), 
CBIRTH DATE ,
CADDRESS VARCHAR2(50),
CRDATE DATE DEFAULT SYSDATE
);
--MANAGER 삭제 생성
DROP TABLE MANAGER;
CREATE TABLE MANAGER(
MID VARCHAR2(50) PRIMARY KEY,
MPW VARCHAR2(50) NOT NULL,
MNAME VARCHAR2(50) NOT NULL
);


--FILEBOARD 삭제 생성
DROP TABLE FILEBOARD;
--시퀀스 삭제 생성
DROP SEQUENCE FILEBOARD_SEQ;
CREATE SEQUENCE FILEBOARD_SEQ
  MAXVALUE 9999999
  NOCACHE
  NOCYCLE;
  
  CREATE TABLE FILEBOARD(
  FNUM NUMBER(7) PRIMARY KEY,
  CID VARCHAR2(50) REFERENCES CUSTOMER(CID),
  MID VARCHAR2(50) REFERENCES MANAGER(MID),
  FSUBJECT      VARCHAR2(250) NOT NULL,  -- 글제목
  FCONTENT      VARCHAR2(4000) ,   -- 글내용
  FFILENAME      VARCHAR2(50),  -- 첨부파일이름
  FHIT                 NUMBER(7) DEFAULT 0  NOT NULL, -- 글 조회수
  FREF                NUMBER(7)   NOT NULL, -- 글그룹
  FRE_STEP         NUMBER(7)   NOT NULL, --그룹내 출력순서
  FRE_LEVEL        NUMBER(7)   NOT NULL, --들여쓰기 정도
  FIP                     VARCHAR2(50) NOT NULL, 
  FRDATE              DATE    DEFAULT SYSDATE  NOT NULL -- 글 등록 시점
  
  );
  SELECT * FROM FILEBOARD;
  
  --CUSTOMER
  --1. 회원가입
  INSERT INTO CUSTOMER(CID, CPW, CNAME, CEMAIL, CIMAGE1, CBIRTH, CADDRESS)
    VALUES('aaa','111','오동준','kok@a.com',NULL,'1855-10-20','강남구');
    SELECT * FROM CUSTOMER WHERE CID = 'aaa';
    
    INSERT INTO CUSTOMER(CID, CPW, CNAME, CEMAIL, CIMAGE1, CBIRTH, CADDRESS)
    VALUES('bbb','111','오석구','abc@a.com',NULL,'1930-10-11','제주');
    SELECT * FROM CUSTOMER WHERE CID = 'bbb';
    
    INSERT INTO CUSTOMER(CID, CPW, CNAME, CEMAIL, CIMAGE1, CBIRTH, CADDRESS)
    VALUES('ccc','111','오장혁','zds@a.com',NULL,'2000-03-20','부산');
    SELECT * FROM CUSTOMER WHERE CID = 'ccc';
    
  --2.로그인
  SELECT * FROM CUSTOMER WHERE CID='aaa' AND CPW='111';
  
  --3.회원정보수정 
  UPDATE CUSTOMER SET CPW='111',
                                CNAME='호로록',
                                CEMAIL ='GG@GG',
                                CADDRESS    = '제주'
                                WHERE CID = 'aaa';
 -- FILEBOARD
 --1.글쓰기
 INSERT INTO FILEBOARD (FNUM,CID,FSUBJECT,FCONTENT,FFILENAME,FHIT,FREF,FRE_STEP,
  FRE_LEVEL,FIP) 
      VALUES(FILEBOARD_SEQ.NEXTVAL,'aaa','글1','본문1',NULL,0,
           FILEBOARD_SEQ.CURRVAL,0,0,'192.168');
INSERT INTO FILEBOARD (FNUM,CID,FSUBJECT,FCONTENT,FFILENAME,FHIT,FREF,FRE_STEP,
  FRE_LEVEL,FIP) 
      VALUES(FILEBOARD_SEQ.NEXTVAL,'bbb','글2','본문2',NULL,0,
           FILEBOARD_SEQ.CURRVAL,0,0,'192.168');
INSERT INTO FILEBOARD (FNUM,CID,FSUBJECT,FCONTENT,FFILENAME,FHIT,FREF,FRE_STEP,
  FRE_LEVEL,FIP) 
      VALUES(FILEBOARD_SEQ.NEXTVAL,'ccc','글3','본문3',NULL,0,
           FILEBOARD_SEQ.CURRVAL,0,0,'192.168');


 --2.글목록
 
SELECT * FROM FILEBOARD;             
SELECT *
       FROM (SELECT ROWNUM RN, A.*
                FROM (SELECT F.*,CNAME, CEMAIL 
                         FROM FILEBOARD F, CUSTOMER C 
                             WHERE F.CID = C.CID
                                ORDER BY FREF DESC, FRE_STEP) A)
                    WHERE RN BETWEEN 1 AND 5;
--3. 등록된 글수
SELECT COUNT(*) FROM FILEBOARD;
 
 --4. 글 상세보기 
 SELECT * FROM FILEBOARD WHERE FNUM=3;
 
 SELECT F.*, CNAME, CEMAIL 
                FROM FILEBOARD F, CUSTOMER C 
                    WHERE F.CID = C.CID
                        AND FNUM=2;
-- 5. 조회수 올리기
UPDATE FILEBOARD SET FHIT = FHIT+1 WHERE FNUM =1;

-- 6. 글 삭제
DELETE FROM FILEBOARD WHERE FNUM=3 ;
--ROLLBACK;

COMMIT;
SELECT * FROM MANAGER;

-- 관리자 MANAGER
--1.관리자 등록

INSERT INTO MANAGER(MID , MPW , MNAME) VALUES ('manager','111','관리자');
--1.관리자 로그인
SELECT * FROM MANAGER WHERE MID='manager' AND MPW='111';
--2.관리자 답변글 쓰기전 STEP A
UPDATE FILEBOARD SET FRE_STEP = FRE_STEP +1 WHERE FREF=3 AND FRE_STEP>0 ;


--5.답변글 쓰기
INSERT INTO FILEBOARD (FNUM, MID,FSUBJECT , FCONTENT,FFILENAME,FREF,FRE_STEP,
        FRE_LEVEL,FIP) 
            VALUES(FILEBOARD_SEQ.NEXTVAL,'manager','글1-1','답',NULL,1,1,1,'192');


SELECT * FROM FILEBOARD;




