-- scott2로 들어와 딕셔너리 뷰 확인

SHOW USER;
SELECT * FROM USER_TABLES; -- SCOTT2가 가지고 있는 테이블     ?????????

SELECT * FROM ALL_TABLES; -- SCOTT2가 접근가능한 테이블 ?????????


SELECT * FROM ALL_TABLES WHERE TABLE_NAME IN ('DEPT' , 'EMP');

SELECT * FROM SCOTT.EMP;

SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D WHERE E.DEPTNO=D.DEPTNO;
EXIT;

-- ★ ★ ★ DML(SELECT, INSERT, UPDATE, DELETE) ★ ★ ★
-- 1. INSERT INTO 테이블명 VALUES ( 값1, 값2, 값3, ...);
SELECT * FROM DEPT;
-- INSERT INTO테이블명( 필드명1, 필드명2, ..) VALUES ( 값1, 값2, ..) ;
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES (50, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT01 (DEPTNO,DNAME, LOC) VALUES (60,'IT','SEOUL');

INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES (70,'OPERATIO'); -- 일부 필드데이터만 넣고싶을때 

INSERT INTO DEPT01 (DEPTNO, DNAME , LOC) VALUES (80, 'HR',NULL) ; -- 명시적으로 NULL 추가

INSERT INTO DEPT01  VALUES (90,'SALES',NULL) ; -- 명시적으로 NULL 추가

-- 서브쿼리를 이용한 INSERT 
INSERT INTO DEPT01 SELECT * FROM DEPT; -- DEPT있는게 DEPT01로 들어감 


-- 트랜잭션 명령어 (DML 명령어만)
COMMIT;

