--2¹ø ¹®Á¦

DROP SEQUENCE CUS_LEVEL_SEQ;
CREATE SEQUENCE CUS_LEVEL_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;


CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(30) NOT NULL
    );
    SELECT * FROM CUS_LEVEL;
    
     INSERT INTO CUS_LEVEL(LEVELNO,LEVELNAME) VALUES(1,'VVIP');
    INSERT INTO CUS_LEVEL(LEVELNO,LEVELNAME) VALUES(2,'VIP');
    INSERT INTO CUS_LEVEL(LEVELNO,LEVELNAME) VALUES(3,'NORMAL');
    INSERT INTO CUS_LEVEL(LEVELNO,LEVELNAME) VALUES(4,'BLACK');
 
 CREATE TABLE CUSTOMER(
    CNO     NUMBER(2) PRIMARY KEY,
    CNAME VARCHAR(30) NOT NULL,
    JOINDATE     DATE DEFAULT SYSDATE,
    PHONE VARCHAR(50) UNIQUE,
    mPOINT  NUMBER(4) CHECK(mPOINT>=0),
     LEVELNO NUMBER(2) NOT NULL,
    FOREIGN KEY(LEVELNO) REFERENCES CUS_LEVEL(LEVELNO)
    );
    DROP TABLE CUSTOMER;
  SELECT * FROM CUSTOMER;
   INSERT INTO CUSTOMER ( CNO, CNAME,  JOINDATE ,PHONE,mPOINT,LEVELNO) 
             VALUES (MEMBER_SEQ.NEXTVAL ,'È«±æµ¿' , '2022-03-10', '010-9999-9999',0,1);
    
   INSERT INTO CUSTOMER ( CNO, CNAME,  JOINDATE ,PHONE,mPOINT,LEVELNO) 
             VALUES (MEMBER_SEQ.NEXTVAL ,'ÀÌÃ¶¼ö' , '2022-04-19', '010-8888-8888',NULL,2);
  
  SELECT * FROM CUSTOMER M ,CUS_LEVEL L 
             WHERE M.LEVELNO = L.LEVELNO;
