DROP SEQUENCE FRIEND_SEQ;
DROP TABLE FRIEND ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE FRIEND(
NO     NUMBER(5)  PRIMARY KEY,
NAME VARCHAR2(30) NOT NULL,
TEL    VARCHAR2(30) NOT NULL
);
--1.모든정보출력
SELECT * FROM FRIEND;
--2.친구 추가
INSERT INTO FRIEND (NO, NAME, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL ,'오동준' ,'010-9999-9999' );
--3.아디 전번으로 검색
SELECT * FROM FRIEND WHERE NAME='오동준' AND TEL='010-9999-9999';