DROP SEQUENCE FRIEND_SEQ;
DROP TABLE FRIEND ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE FRIEND(
NO     NUMBER(5)  PRIMARY KEY,
NAME VARCHAR2(30) NOT NULL,
TEL    VARCHAR2(30) NOT NULL
);
SELECT * FROM FRIEND;